name: classmate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.3
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  badges: ^3.1.1
  shimmer: ^2.0.0
  toggle_switch: ^2.1.0
  pinput: ^2.2.31
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  custom_pop_up_menu: ^1.2.4
  expandable_text: ^2.3.0

  # Networking and API
  http: ^0.13.5
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^4.0.1
  url_launcher: ^6.1.12

  # State Management and Utilities
  flutter_riverpod: ^2.2.0
  get: ^4.7.2
  fpdart: ^0.5.0
  email_validator: ^2.1.16
  intl: ^0.18.1
  flutter_intl: ^0.0.1

  # Storage and Caching
  shared_preferences: ^2.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  # File and Media Handling
  image_picker: ^1.1.2  # Latest as of March 2025, check pub.dev for updates
  file_picker: ^9.2.1
  image: ^4.1.7
  flutter_document_picker: ^5.2.3
  flutter_dropzone: ^3.0.5
  mime: ^1.0.4
  syncfusion_flutter_pdfviewer: ^20.4.54

  # Firebase and Analytics
  firebase_core: ^2.9.0
  firebase_auth:
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.4.3
  google_sign_in: ^6.1.0

  # Notifications
  awesome_notifications: ^0.8.2
  onesignal_flutter: ^3.5.1

  # Navigation and Routing
  go_router: ^6.5.0
  url_strategy:

  # Miscellaneous
  app_settings: ^4.2.0
  sentry_flutter: ^7.14.0
  flutter_lints: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/appLogoWithTittle.png
    - assets/png/Class Master (Logo with texts).png
    - assets/png/newSplash.png
    - assets/png/192 x 192.png
    - assets/png/frem192LogoWithTittle.png
    - assets/png/logo.png
    - assets/png/logo_with_padding.png
    - assets/logo/
    - assets/logo/white_logo.png
    - assets/png/wa.png
    - shorebird.yaml

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_icons:
  android: true
  image_path: "assets/png/logo_with_padding.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/frem192LogoWithTittle.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#ffffff"
    android_gravity: center