// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDlJSWUPr3CDVbUoxA-Ag_FKnAS3GOi0',
    appId: '1:837394216188:web:db9045a5cb6e18618dd379',
    messagingSenderId: '837394216188',
    projectId: 'rutinapp-cadc1',
    authDomain: 'rutinapp-cadc1.firebaseapp.com',
    storageBucket: 'rutinapp-cadc1.appspot.com',
    measurementId: 'G-98CE05FZG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD50R66U5baOtkiMfN7CZvuOYjvbb7pVKU',
    appId: '1:837394216188:android:18115f8313208a028dd379',
    messagingSenderId: '837394216188',
    projectId: 'rutinapp-cadc1',
    storageBucket: 'rutinapp-cadc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbbIMg0jaarhxp9N2-jJULAsMlISsJxUM',
    appId: '1:837394216188:ios:cf372be403aa58668dd379',
    messagingSenderId: '837394216188',
    projectId: 'rutinapp-cadc1',
    storageBucket: 'rutinapp-cadc1.appspot.com',
    iosClientId: '837394216188-8j4gh2cn1b5recm3vjfpe0b1vbge7bkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.table',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbbIMg0jaarhxp9N2-jJULAsMlISsJxUM',
    appId: '1:837394216188:ios:cf372be403aa58668dd379',
    messagingSenderId: '837394216188',
    projectId: 'rutinapp-cadc1',
    storageBucket: 'rutinapp-cadc1.appspot.com',
    iosClientId: '837394216188-8j4gh2cn1b5recm3vjfpe0b1vbge7bkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.table',
  );
}
